// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'message.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$Message {

/// Specifies the sender of the message, either [Role.user] or [Role.agent].
 Role get role;/// A list of content [Part]s that make up the message body.
///
/// A message can be composed of multiple parts of different types
/// (e.g., text, files, structured data).
 List<Part> get parts;/// Optional metadata for extensions, as a map where the key is an
/// extension-specific identifier.
 Map<String, Object?>? get metadata;/// Optional list of URIs for extensions that are relevant to this message.
 List<String>? get extensions;/// Optional list of other task IDs that this message references for
/// additional context.
 List<String>? get referenceTaskIds;/// A unique identifier for this message, typically a UUID, generated by the
/// sender.
 String get messageId;/// The ID of the task this message belongs to.
///
/// This can be omitted for the initial message in a new task interaction.
 String? get taskId;/// An identifier used to group related messages and tasks, such as within
/// a single conversation or session.
 String? get contextId;/// The type discriminator for this object, always 'message'.
 String get kind;
/// Create a copy of Message
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$MessageCopyWith<Message> get copyWith => _$MessageCopyWithImpl<Message>(this as Message, _$identity);

  /// Serializes this Message to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is Message&&(identical(other.role, role) || other.role == role)&&const DeepCollectionEquality().equals(other.parts, parts)&&const DeepCollectionEquality().equals(other.metadata, metadata)&&const DeepCollectionEquality().equals(other.extensions, extensions)&&const DeepCollectionEquality().equals(other.referenceTaskIds, referenceTaskIds)&&(identical(other.messageId, messageId) || other.messageId == messageId)&&(identical(other.taskId, taskId) || other.taskId == taskId)&&(identical(other.contextId, contextId) || other.contextId == contextId)&&(identical(other.kind, kind) || other.kind == kind));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,role,const DeepCollectionEquality().hash(parts),const DeepCollectionEquality().hash(metadata),const DeepCollectionEquality().hash(extensions),const DeepCollectionEquality().hash(referenceTaskIds),messageId,taskId,contextId,kind);

@override
String toString() {
  return 'Message(role: $role, parts: $parts, metadata: $metadata, extensions: $extensions, referenceTaskIds: $referenceTaskIds, messageId: $messageId, taskId: $taskId, contextId: $contextId, kind: $kind)';
}


}

/// @nodoc
abstract mixin class $MessageCopyWith<$Res>  {
  factory $MessageCopyWith(Message value, $Res Function(Message) _then) = _$MessageCopyWithImpl;
@useResult
$Res call({
 Role role, List<Part> parts, Map<String, Object?>? metadata, List<String>? extensions, List<String>? referenceTaskIds, String messageId, String? taskId, String? contextId, String kind
});




}
/// @nodoc
class _$MessageCopyWithImpl<$Res>
    implements $MessageCopyWith<$Res> {
  _$MessageCopyWithImpl(this._self, this._then);

  final Message _self;
  final $Res Function(Message) _then;

/// Create a copy of Message
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? role = null,Object? parts = null,Object? metadata = freezed,Object? extensions = freezed,Object? referenceTaskIds = freezed,Object? messageId = null,Object? taskId = freezed,Object? contextId = freezed,Object? kind = null,}) {
  return _then(_self.copyWith(
role: null == role ? _self.role : role // ignore: cast_nullable_to_non_nullable
as Role,parts: null == parts ? _self.parts : parts // ignore: cast_nullable_to_non_nullable
as List<Part>,metadata: freezed == metadata ? _self.metadata : metadata // ignore: cast_nullable_to_non_nullable
as Map<String, Object?>?,extensions: freezed == extensions ? _self.extensions : extensions // ignore: cast_nullable_to_non_nullable
as List<String>?,referenceTaskIds: freezed == referenceTaskIds ? _self.referenceTaskIds : referenceTaskIds // ignore: cast_nullable_to_non_nullable
as List<String>?,messageId: null == messageId ? _self.messageId : messageId // ignore: cast_nullable_to_non_nullable
as String,taskId: freezed == taskId ? _self.taskId : taskId // ignore: cast_nullable_to_non_nullable
as String?,contextId: freezed == contextId ? _self.contextId : contextId // ignore: cast_nullable_to_non_nullable
as String?,kind: null == kind ? _self.kind : kind // ignore: cast_nullable_to_non_nullable
as String,
  ));
}

}


/// Adds pattern-matching-related methods to [Message].
extension MessagePatterns on Message {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _Message value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _Message() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _Message value)  $default,){
final _that = this;
switch (_that) {
case _Message():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _Message value)?  $default,){
final _that = this;
switch (_that) {
case _Message() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function( Role role,  List<Part> parts,  Map<String, Object?>? metadata,  List<String>? extensions,  List<String>? referenceTaskIds,  String messageId,  String? taskId,  String? contextId,  String kind)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _Message() when $default != null:
return $default(_that.role,_that.parts,_that.metadata,_that.extensions,_that.referenceTaskIds,_that.messageId,_that.taskId,_that.contextId,_that.kind);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function( Role role,  List<Part> parts,  Map<String, Object?>? metadata,  List<String>? extensions,  List<String>? referenceTaskIds,  String messageId,  String? taskId,  String? contextId,  String kind)  $default,) {final _that = this;
switch (_that) {
case _Message():
return $default(_that.role,_that.parts,_that.metadata,_that.extensions,_that.referenceTaskIds,_that.messageId,_that.taskId,_that.contextId,_that.kind);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function( Role role,  List<Part> parts,  Map<String, Object?>? metadata,  List<String>? extensions,  List<String>? referenceTaskIds,  String messageId,  String? taskId,  String? contextId,  String kind)?  $default,) {final _that = this;
switch (_that) {
case _Message() when $default != null:
return $default(_that.role,_that.parts,_that.metadata,_that.extensions,_that.referenceTaskIds,_that.messageId,_that.taskId,_that.contextId,_that.kind);case _:
  return null;

}
}

}

/// @nodoc
@JsonSerializable()

class _Message implements Message {
  const _Message({required this.role, required final  List<Part> parts, final  Map<String, Object?>? metadata, final  List<String>? extensions, final  List<String>? referenceTaskIds, required this.messageId, this.taskId, this.contextId, this.kind = 'message'}): _parts = parts,_metadata = metadata,_extensions = extensions,_referenceTaskIds = referenceTaskIds;
  factory _Message.fromJson(Map<String, dynamic> json) => _$MessageFromJson(json);

/// Specifies the sender of the message, either [Role.user] or [Role.agent].
@override final  Role role;
/// A list of content [Part]s that make up the message body.
///
/// A message can be composed of multiple parts of different types
/// (e.g., text, files, structured data).
 final  List<Part> _parts;
/// A list of content [Part]s that make up the message body.
///
/// A message can be composed of multiple parts of different types
/// (e.g., text, files, structured data).
@override List<Part> get parts {
  if (_parts is EqualUnmodifiableListView) return _parts;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(_parts);
}

/// Optional metadata for extensions, as a map where the key is an
/// extension-specific identifier.
 final  Map<String, Object?>? _metadata;
/// Optional metadata for extensions, as a map where the key is an
/// extension-specific identifier.
@override Map<String, Object?>? get metadata {
  final value = _metadata;
  if (value == null) return null;
  if (_metadata is EqualUnmodifiableMapView) return _metadata;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableMapView(value);
}

/// Optional list of URIs for extensions that are relevant to this message.
 final  List<String>? _extensions;
/// Optional list of URIs for extensions that are relevant to this message.
@override List<String>? get extensions {
  final value = _extensions;
  if (value == null) return null;
  if (_extensions is EqualUnmodifiableListView) return _extensions;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(value);
}

/// Optional list of other task IDs that this message references for
/// additional context.
 final  List<String>? _referenceTaskIds;
/// Optional list of other task IDs that this message references for
/// additional context.
@override List<String>? get referenceTaskIds {
  final value = _referenceTaskIds;
  if (value == null) return null;
  if (_referenceTaskIds is EqualUnmodifiableListView) return _referenceTaskIds;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(value);
}

/// A unique identifier for this message, typically a UUID, generated by the
/// sender.
@override final  String messageId;
/// The ID of the task this message belongs to.
///
/// This can be omitted for the initial message in a new task interaction.
@override final  String? taskId;
/// An identifier used to group related messages and tasks, such as within
/// a single conversation or session.
@override final  String? contextId;
/// The type discriminator for this object, always 'message'.
@override@JsonKey() final  String kind;

/// Create a copy of Message
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$MessageCopyWith<_Message> get copyWith => __$MessageCopyWithImpl<_Message>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$MessageToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _Message&&(identical(other.role, role) || other.role == role)&&const DeepCollectionEquality().equals(other._parts, _parts)&&const DeepCollectionEquality().equals(other._metadata, _metadata)&&const DeepCollectionEquality().equals(other._extensions, _extensions)&&const DeepCollectionEquality().equals(other._referenceTaskIds, _referenceTaskIds)&&(identical(other.messageId, messageId) || other.messageId == messageId)&&(identical(other.taskId, taskId) || other.taskId == taskId)&&(identical(other.contextId, contextId) || other.contextId == contextId)&&(identical(other.kind, kind) || other.kind == kind));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,role,const DeepCollectionEquality().hash(_parts),const DeepCollectionEquality().hash(_metadata),const DeepCollectionEquality().hash(_extensions),const DeepCollectionEquality().hash(_referenceTaskIds),messageId,taskId,contextId,kind);

@override
String toString() {
  return 'Message(role: $role, parts: $parts, metadata: $metadata, extensions: $extensions, referenceTaskIds: $referenceTaskIds, messageId: $messageId, taskId: $taskId, contextId: $contextId, kind: $kind)';
}


}

/// @nodoc
abstract mixin class _$MessageCopyWith<$Res> implements $MessageCopyWith<$Res> {
  factory _$MessageCopyWith(_Message value, $Res Function(_Message) _then) = __$MessageCopyWithImpl;
@override @useResult
$Res call({
 Role role, List<Part> parts, Map<String, Object?>? metadata, List<String>? extensions, List<String>? referenceTaskIds, String messageId, String? taskId, String? contextId, String kind
});




}
/// @nodoc
class __$MessageCopyWithImpl<$Res>
    implements _$MessageCopyWith<$Res> {
  __$MessageCopyWithImpl(this._self, this._then);

  final _Message _self;
  final $Res Function(_Message) _then;

/// Create a copy of Message
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? role = null,Object? parts = null,Object? metadata = freezed,Object? extensions = freezed,Object? referenceTaskIds = freezed,Object? messageId = null,Object? taskId = freezed,Object? contextId = freezed,Object? kind = null,}) {
  return _then(_Message(
role: null == role ? _self.role : role // ignore: cast_nullable_to_non_nullable
as Role,parts: null == parts ? _self._parts : parts // ignore: cast_nullable_to_non_nullable
as List<Part>,metadata: freezed == metadata ? _self._metadata : metadata // ignore: cast_nullable_to_non_nullable
as Map<String, Object?>?,extensions: freezed == extensions ? _self._extensions : extensions // ignore: cast_nullable_to_non_nullable
as List<String>?,referenceTaskIds: freezed == referenceTaskIds ? _self._referenceTaskIds : referenceTaskIds // ignore: cast_nullable_to_non_nullable
as List<String>?,messageId: null == messageId ? _self.messageId : messageId // ignore: cast_nullable_to_non_nullable
as String,taskId: freezed == taskId ? _self.taskId : taskId // ignore: cast_nullable_to_non_nullable
as String?,contextId: freezed == contextId ? _self.contextId : contextId // ignore: cast_nullable_to_non_nullable
as String?,kind: null == kind ? _self.kind : kind // ignore: cast_nullable_to_non_nullable
as String,
  ));
}


}

// dart format on
