// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:freezed_annotation/freezed_annotation.dart';

import 'part.dart';

part 'message.freezed.dart';
part 'message.g.dart';

/// Identifies the sender of a [Message].
enum Role {
  /// The message originated from the user (i.e., the A2A client).
  user,

  /// The message originated from the agent (i.e., the A2A server).
  agent,
}

/// Represents a single communication exchange within an A2A interaction.
///
/// Messages are the fundamental unit of communication, used for sending
/// instructions, prompts, data, and replies between a client and an agent.
/// A message consists of one or more [Part]s, allowing for rich content.
@freezed
abstract class Message with _$Message {
  /// Creates a [Message] instance.
  const factory Message({
    /// Specifies the sender of the message, either [Role.user] or [Role.agent].
    required Role role,

    /// A list of content [Part]s that make up the message body.
    ///
    /// A message can be composed of multiple parts of different types
    /// (e.g., text, files, structured data).
    required List<Part> parts,

    /// Optional metadata for extensions, as a map where the key is an
    /// extension-specific identifier.
    Map<String, Object?>? metadata,

    /// Optional list of URIs for extensions that are relevant to this message.
    List<String>? extensions,

    /// Optional list of other task IDs that this message references for
    /// additional context.
    List<String>? referenceTaskIds,

    /// A unique identifier for this message, typically a UUID, generated by the
    /// sender.
    required String messageId,

    /// The ID of the task this message belongs to.
    ///
    /// This can be omitted for the initial message in a new task interaction.
    String? taskId,

    /// An identifier used to group related messages and tasks, such as within
    /// a single conversation or session.
    String? contextId,

    /// The type discriminator for this object, always 'message'.
    @Default('message') String kind,
  }) = _Message;

  /// Deserializes a [Message] instance from a JSON object.
  factory Message.fromJson(Map<String, Object?> json) =>
      _$MessageFromJson(json);
}
