// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:freezed_annotation/freezed_annotation.dart';

import 'message.dart';
import 'part.dart';

part 'task.freezed.dart';

part 'task.g.dart';

/// Represents a stateful operation or conversation between a client and an
/// agent.
///
/// A [Task] encapsulates the entire lifecycle of an interaction, including its
/// current status, history of messages, and any generated artifacts.
@freezed
abstract class Task with _$Task {
  /// Creates a [Task] instance.
  const factory Task({
    /// A unique identifier (e.g., UUID) for the task.
    ///
    /// This ID is typically generated by the server when a new task is created.
    required String id,

    /// A server-generated unique identifier (e.g., UUID) for grouping related
    /// tasks or interactions, forming a conversation context.
    required String contextId,

    /// The current status of the task, including its state and any associated
    /// message.
    required TaskStatus status,

    /// An optional list of [Message] objects representing the conversation
    /// history of the task.
    List<Message>? history,

    /// An optional collection of [Artifact]s produced by the agent during the
    /// task's execution.
    List<Artifact>? artifacts,

    /// Optional metadata for extensions, as a map where the key is an
    /// extension-specific identifier.
    Map<String, Object?>? metadata,

    /// The timestamp of the last update to the task, in milliseconds since the
    /// Unix epoch.
    int? lastUpdated,

    /// The type discriminator for this object, always 'task'.
    @Default('task') String kind,
  }) = _Task;

  /// Deserializes a [Task] instance from a JSON object.
  factory Task.fromJson(Map<String, Object?> json) => _$TaskFromJson(json);
}

/// Represents the status of a [Task] at a specific point in time.
@freezed
abstract class TaskStatus with _$TaskStatus {
  /// Creates a [TaskStatus] instance.
  const factory TaskStatus({
    /// The current state in the task's lifecycle.
    required TaskState state,

    /// An optional, human-readable [Message] providing more details about the
    /// current status (e.g., an error message or a prompt for input).
    Message? message,

    /// The timestamp when this status was recorded, in milliseconds since the
    /// Unix epoch.
    String? timestamp,
  }) = _TaskStatus;

  /// Deserializes a [TaskStatus] instance from a JSON object.
  factory TaskStatus.fromJson(Map<String, Object?> json) =>
      _$TaskStatusFromJson(json);
}

/// Defines the possible lifecycle states of a [Task].
@JsonEnum(fieldRename: FieldRename.kebab)
enum TaskState {
  /// The task has been received by the server but not yet started.
  submitted,

  /// The agent is actively processing the task.
  working,

  /// The task is paused, awaiting further input from the client.
  inputRequired,

  /// The task has been successfully completed by the agent.
  completed,

  /// The task was canceled, typically by a client request.
  canceled,

  /// The task failed due to an error during execution.
  failed,

  /// The task was rejected by the agent before execution began (e.g., due to
  /// invalid parameters or permissions).
  rejected,

  /// The task cannot proceed without additional authentication or
  /// authorization.
  authRequired,

  /// The task is in an unknown or indeterminate state.
  unknown,
}

/// Represents a file, data structure, or other resource generated by an agent
/// during a [Task].
@freezed
abstract class Artifact with _$Artifact {
  /// Creates an [Artifact] instance.
  const factory Artifact({
    /// A unique identifier for this artifact within the scope of the task.
    required String artifactId,

    /// An optional, human-readable name for the artifact.
    String? name,

    /// An optional, human-readable description of the artifact's content or
    /// purpose.
    String? description,

    /// A list of [Part] objects that constitute the content of the artifact.
    required List<Part> parts,

    /// Optional metadata for extensions.
    Map<String, Object?>? metadata,

    /// Optional list of URIs for extensions that are relevant to this artifact.
    List<String>? extensions,
  }) = _Artifact;

  /// Deserializes an [Artifact] instance from a JSON object.
  factory Artifact.fromJson(Map<String, Object?> json) =>
      _$ArtifactFromJson(json);
}
