name: eval-workflow

on:
  push: 
    # Workflow runs on push to any branch.
  schedule:
    - cron: "0 * * * *" # hourly

# TODO(polina-c): add steps that run tests

jobs:
  eval-job:
    runs-on: ubuntu-latest
    environment: eval
    steps:
      - name: Check that REPO_GEMINI_API_KEY is set and available
        env:
          GEMINI_API_KEY: ${{ secrets.REPO_GEMINI_API_KEY }}
        run: |
          echo "GEMINI_API_KEY has ${#GEMINI_API_KEY} characters"
          
        
          
          
          

