name: eval-workflow

on:
  push: 
    # Workflow runs on push to any branch.
  schedule:
    - cron: "0 * * * *" # hourly

# TODO(polina-c): add steps that run tests

jobs:
  eval-job:
    runs-on: ubuntu-latest
    environment: eval
    steps:
      - name: Check that key is available
        run: |
          echo "ENV_KEY has ${#ENV_KEY} characters"
          echo "REPO_KEY has ${#REPO_KEY} characters"
          
        env:
          ENV_KEY: ${{ secrets.ENV_GEMINI_API_KEY }}
          REPO_KEY: ${{ secrets.REPO_GEMINI_API_KEY }}
          
          

