# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: my-test-env
    steps:
    - uses: actions/checkout@v2

    - name: secret
      env:
        MY_TEST_VAR: ${{ secrets.MY_TEST_VAR }}
        MY_VAR_NAME: ${{ vars.MY_VAR_NAME }}
      run: |
        echo "MY_TEST_VAR has ${#MY_TEST_VAR} chars"
        echo 'Hi ${{ vars.MY_VAR_NAME }}'
        echo "Hi $MY_VAR_NAME"
