[project]
name = "verdure-server"
version = "0.1.0"
description = "A top-level project to manage the Verdure server example."
dependencies = [
    "verdure",
    "a2ui-ext",
]

[tool.uv.workspace]
members = ["a2ui_extension", "verdure"]

[tool.uv.sources]
verdure = { workspace = true }
a2ui-ext = { workspace = true }
